### ISSUE TITLE
权限管理有问题不在自己名下的产品也可以被获取到且会泄漏其他用户隐私数据

### ISSUE THREAD

**Issue by xqin** [jeodiong/TodoKit-api#2]
RT(如题)

具体代码就不提了, 自己看你后面的API,基本上只要是登陆用户就有权限调用,没有判断当前用户是否有能力调用.

或者也许这个产品就是这么设计的? 如果是的话, 请忽略 这个 issue.

**Comment by xqin** [comment]
另外你的部分接口,都是在 `_md.signinRequired` 验证完成之后, 才执行的.
而你有部分代码在这个验证完成之后, 又一次调用 `_md.decodeToken` 来验证 `access_token` 的有效性.
属于重复调用, 因为前面如果验证不通过, 是不会走到后面的逻辑.

完全可以在 `signinRequired` 里验证通过之后, 把 `decode` 出来的数据, 挂在 `req` 上, 然后在后续的流程中, 直接从`req`中取数据, 从而不用再次 `decodeToken` 来获取解密后的数据.

再另外 `signinRequired` 可以直接调用 `decodeToken` 然后在 `callback` 中继续后面的逻辑, 而不是把 `decodeToken` 中的逻辑在 `signinRequired` 里面再写一遍.

**Comment by joe-lz** [comment]
第一个问题，一开始就没写权限，后来没时间加就忘了，第二个我看看

**Comment by joe-lz** [comment]
谢谢你提的问题，会迅速改进的，还有问题尽量提😂

**Comment by joe-lz** [comment]
已解决

**Comment by xqin** [comment]
@jeodiong 不继续开源了吗? 目前并没有看到修复后的代码提交到github上.

**Comment by joe-lz** [comment]
刚才传上去了
