### ISSUE TITLE
加密KEY泄漏建议你更新你目前生产环境config.js里面所有的key

### ISSUE THREAD

**Issue by xqin** [jeodiong/TodoKit-api#3]
https://github.com/jeodiong/TodoKit-api/commit/d86ee10737f5b105bc43ab3ddec499a0a927bef4#diff-1550216a33699095db2b62f0261dab5dR1

虽然你后面有`commit`修改了`config.js`里面的内容， 但 `git` 的版本管理功能完整的记录了你改之前的内容。
虽然不知道有效性， 但仍然建议你重新 ***生成/更换*** `jwt/wilddog/qiniu` 的`Key`。
假如里面的`key`是你目前生产环境正在使用的，那么其他人可以直接调用你的 `wilddog` 的短信接口。
`qiniu`的云存储，以及自己构造 `access_token` 来请求你的接口，你后台的所有验证都是基于 `jwt` 加密的.

**Comment by joe-lz** [comment]
已替换😄
